### ISSUE TITLE
Text

### ISSUE THREAD

**Issue by Jinsujin** [Jinsujin/SwiftUI#2]
[👉 Document](https://developer.apple.com/documentation/swiftui/text/)
[Apple 에서 사용가능한 System font 목록](https://developer.apple.com/fonts/system-fonts/#document)

> Text View 를 사용해 문자열을 꾸미는 다양한 modifier 가 존재한다.
>
> modifier 는 중첩해서 사용함으로서 다양하게 표시할 수 있도록 도와준다.

### Custom Font 사용하기
1. 폰트 파일을 프로젝트에 넣기 (Add to target 체크)
2. info.plist 에 `Fonts provided by application` 속성을 추가하고, Item 에 파일명(폰트명.ttf) 을 명시
   - 확장자를 반드시 기입해야 함 
4. `custom("폰트명")` modifier를 사용해 폰트사용

  ```swift
  .font(.custom("Avenir Heavy", size: 16))
  ```
    
<br/>

### (참고)폰트를 찾지 못할때 
폰트의 파일명과 실제 시스템에서 사용되는 이름이 달라서 가져오지 못하는 경우가 있다.
이럴때는 아래코드를 사용해, 사용가능한 모든 폰트명과 패밀리폰트명을 알아낼 수 있다.

```swift
            .onAppear {
                for family: String in UIFont.familyNames {
                        print(family)
                        for names : String in UIFont.fontNames(forFamilyName: family){
                            print("=== \(names)")
                        }
                    }
            }
```

- ex) 폰트 파일명은 `Jost-VariableFont_wght`이지만, 불러올때 사용하는 폰트명은 `Jost`
```
Jost
=== Jost-Regular
=== JostRoman-Thin
=== JostRoman-ExtraLight
=== JostRoman-Light
=== JostRoman-Medium
=== JostRoman-SemiBold
=== JostRoman-Bold
=== JostRoman-ExtraBold
=== JostRoman-Black
```

**Comment by GangWoon** [comment]
반갑습니다:)

**Comment by Jinsujin** [comment]
SwiftUI 로 생성한 프로젝트에서 plist.info 파일은 만들어지지 않는다.
- Targets -> `info` tab -> 'Custom iOS Target Properties' 에서 값을 수정할 수 있다.

- [참고](https://useyourloaf.com/blog/xcode-13-missing-info.plist/)
